### PR TITLE
Release version updates

### PR DESCRIPTION
**Pull request by mohandatla**
Rev version to 2.0.0.5 from 2.0.0.4
Build zip files and update.
Update doc with new zip file names.

### CODE REVIEW

**Comment by jslobodzian** [comment]
Are the "downloads" below more than just a "rename"?

**Comment by gmileka** [comment]
It's weird the .rc files show as binary files...

**Comment by mohandatla** [comment]
> Are the "downloads" below more than just a "rename"? (This is how it shows in codeflow)

These are not renames, these files 

> Are the "downloads" below more than just a "rename"? (This is how it shows in codeflow)

These are new zip files with new binaries not just renames

**Comment by mohandatla** [comment]
> It's weird the .rc files show as binary files...

I did see that the beyond compare showing up correctly the differences, I verified it looks good

**Comment by mohandatla** [comment]
Fixed diagnostic plug-in failure.

**Pull request merged**
